max_parts_to_merge_at_once: [5, 10, 20]
base: [3, 5, 7]
min_size_to_lower_base: [1048576, 5242880, 10485760]
max_size_to_lower_base: [52428800, 104857600, 157286400]
min_age_to_lower_base_at_min_size: [10, 3600, 86400]
min_age_to_lower_base_at_max_size: [10, 3600, 86400]
max_age_to_lower_base_at_min_size: [3600, 86400, 604800]
max_age_to_lower_base_at_max_size: [86400, 604800, 2592000]
min_parts_to_lower_base: [5, 10, 15]
max_parts_to_lower_base: [50]
size_fixed_cost_to_add: [5242880]
enable_heuristic_to_align_parts: [true]
heuristic_to_align_parts_min_ratio_of_sum_size_to_prev_part: [0.9]
heuristic_to_align_parts_max_absolute_difference_in_powers_of_two: [0.5]
heuristic_to_align_parts_max_score_adjustment: [0.75]
min_age_to_force_merge: [0]
enable_heuristic_to_remove_small_parts_at_right: [true]
heuristic_to_remove_small_parts_at_right_max_ratio: [0.01]
max_total_size_to_merge: [20000]
